# Generated by Django 3.0.3 on 2020-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('p', 'primary'), ('se', 'secondary'), ('su', 'success'), ('dn', 'danger'), ('w', 'warning'), ('in', 'info'), ('d', 'dark')], max_length=2, null=True),
        ),
    ]
