# Generated by Django 3.0.4 on 2020-03-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
