# Generated by Django 3.0.4 on 2020-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200307_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
    ]
