# Generated by Django 3.0.4 on 2020-03-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_order_is_refund_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_received_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_start_date',
        ),
    ]
