# Generated by Django 3.0.4 on 2020-03-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200307_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='payment_method',
            field=models.CharField(choices=[('str', 'Card'), ('bks', 'bKash'), ('con', 'Cash On Delivery')], max_length=3),
        ),
    ]
