# Generated by Django 3.0.4 on 2020-03-10 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0019_auto_20200309_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(choices=[('BD', 'Bangladesh')], max_length=2)),
                ('state', models.CharField(choices=[('Chittagong', (('cbra', 'Brahmanbaria'), ('ccom', 'Comilla'), ('clak', 'Lokshmipur'), ('cnoa', 'Noakhali'), ('cfen', 'Feni'), ('ckha', 'Khagrachhari'), ('cran', 'Rangamati'), ('cban', 'Bandarban'), ('cchi', 'Chittagong'), ('ccox', "Cox's Bazar"))), ('Barisal', (('bbra', 'Barisal'), ('bbar', 'Barguna'), ('bhol', 'Bhola'), ('bjal', 'Jhalokati'), ('bpat', 'Patuakhali'), ('bpir', 'Pirojpur'))), ('Dhaka', (('ddha', 'Dhaka'), ('dgha', 'Ghazipur'), ('dkis', 'Kishoreganj'), ('dman', 'Manikganj'), ('dmun', 'Munshiganj'), ('dnar', 'Narayanganj'), ('dnrs', 'Narasingdi'), ('dtan', 'Tangail'), ('dfar', 'Faridpur'), ('dgop', 'Gopalganj'), ('dmad', 'Madaripur'), ('draj', 'Rajbari'), ('dsha', 'Shariatpur')))], max_length=4)),
                ('zip_code', models.CharField(blank=True, max_length=15)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_info',
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='backend.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='backend.Address'),
        ),
    ]
