# Generated by Django 3.0.4 on 2020-03-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20200310_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
